### ISSUE TITLE
Question regarding existing plex servers

### ISSUE THREAD

**Issue by miguemely** [munnerz/kube-plex#101]
This is mostly a question, and not really an issue, but will this work with a *already set up* Plex server or will I need to run it on Kubernetes to get the full functionality?

**Comment by gwyden** [comment]
@miguemely you need to run it in kubernetes.   The shim for the transcoder could be faked out but that will givey ou some very strange behavior unless you can share your media and the transcode and the tmp folders.  Now that I've gotten into the code i think it might be possible to use the shim but not as it stands right now.

**Comment by miguemely** [comment]
> @miguemely you need to run it in kubernetes. The shim for the transcoder could be faked out but that will givey ou some very strange behavior unless you can share your media and the transcode and the tmp folders. Now that I've gotten into the code i think it might be possible to use the shim but not as it stands right now.

Gotcha. I have some Nvidia TK1s and Intel NUCs I wanted to use for this, but would be nice if 10gb was available as well.
