### ISSUE TITLE
Provide option to disable remote transcoding

### ISSUE THREAD

**Issue by munnerz** [munnerz/kube-plex#14]
The chart provided in this repository could be generally useful as a mechanism to deploy Plex on Kubernetes. We should provide an option to disable the remote transcoder functionality (i.e. don't replace Plex Transcoder) so that users can deploy a normal plexmediaserver instance as well. The chart could then potentially be submitted upstream to https://github.com/kubernetes/charts

**Comment by SebastienTolron** [comment]
Hi James ,

Any news on this ? 

That would be pretty cool for people that does not have appropriate volumes.

Thanks !

**Comment by munnerz** [comment]
This is now possible via the values.yaml file!
