### ISSUE TITLE
Looking for servers

### ISSUE THREAD

**Issue by nickray** [munnerz/kube-plex#18]
Hi, this looks great, however... I just deployed this in my home network (with an ingress and rook storage), and upon visiting the application URL, `<url>/web/index.html` is stuck "Looking for servers....". Not sure where to start debugging this; the pod looks happy with its log ending in "Starting Plex Media Server."

**Comment by nickray** [comment]
OK so port-forwarding 32400 to 32400 on the pod and visiting `localhost:32400/web` got me signed in and started.

**Comment by tedder** [comment]
For future googlers, accessing the pod over the load balancer, or ingress, or whatever doesn't work for initial setup. The key is to use `kubectl port-forward` like nickray did. Simply saying "oh, I can access it over 32400" doesn't mean it sees you as local.

I don't know if there's a way to configure this, but yeah.
