### ISSUE TITLE
Scalable-- meaning?

### ISSUE THREAD

**Issue by HammyHavoc** [munnerz/kube-plex#2]
Great repository, James, just curious as to what is meant by scalable; can a transcode be distributed across multiple machines? Or does it simply allow a larger number of concurrent streams?

I've got access to a lot of motherboards with integrated quad-core Atom CPUs, and they're okay, but they seem to struggle with larger media files (buffering), but as a cluster, I'm wondering what the possibilities are.

I've got a bunch of cloud resources too and an unlimited Google Drive account that I'm playing with via Fuse, let me know if you'd like to play with my toys at some point, you definitely have some nice ideas. One server has a symmetrical 700mb connection.

**Comment by yyolk** [comment]
_Elastic transcoder_ a service provided by AWS is elastic aka scalable

**Comment by munnerz** [comment]
Firstly, thanks!

Currently, this doesn't add the ability to distribute a single transcode across multiple machines, it'll simply allow you to run multiple transcodes on different machines, transparently to the user. It's useful if you're running a PMS with multiple users, and not many compute resources. (or alternatively, if you wanted to build an Atom/RPi cluster whereby one transcode could run on each machine and it could easily scale up with the addition of new machines)

I'm unsure if ffmpeg has any support for splitting a single transcode across multiple machines, but if it's possible then you should be able to modify this tool slightly to allow for it.

Sounds like your quad-core Atom boards would work great! You can deal with scheduling and balancing load just as you would with any Kubernetes cluster, by setting resource limits/requests on the pods that plex-elastic-transcoder creates (currently this isn't functionality that plex-elastic-transcoder exposes nicely, you'll need to just modify the PodSpec).

Interested to hear how streaming from Google Drive goes for you - I've considered it in the past but am unsure on their bandwidth restrictions. How's your experience been?
