### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ghost** [munnerz/kube-plex#3]
Does this clienten beingen effected by the error that is taked about here?https://github.com/wnielson/Plex-Remote-Transcoder/issues/27
And does this clientent support multi type cpu. For example some slave are raspberry pi and others are x86 computers?

**Comment by munnerz** [comment]
Hi there, sorry for the late reply on this..

1) No, that issue shouldn't affect plex-elastic-transcoder as we package a Docker image containing the Plex New Transcoder binary, meaning the transcoders themselves are not running the entirety of PMS.

2) Multiple CPU types will be possible (by building a transcoder image for armhf etc.), however there'll need to be a way to specify the different image to run when creating transcode jobs. I'm going to investigate any proposals on Kubernetes around dealing with alt-arch images and probably follow some best practice gained from that.
