### ISSUE TITLE
integrate Tautulli?

### ISSUE THREAD

**Issue by billimek** [munnerz/kube-plex#37]
Is there any interest in adding an _optional_ integration with [Tautulli](https://github.com/Tautulli/Tautulli) in kube-plex?

As the Tautilli (formerly plexpy) implementation requires access to the Plex logs in the plex runtime filesystem, running this as a sidecar seems like a logical choice.

If this is something that would be accepted, I'm happy to take a crack at a PR to implement this feature.

**Comment by Arcanemagus** [comment]
> As the Tautilli (formerly plexpy) implementation requires access to the Plex logs

Tautulli actually has no requirement on access to the Plex logs. In fact the only usage it can get out of them is as a nicer log viewer for the user than the raw files, but that's essentially it. All monitoring of a Plex server is done over a WebSocket connection.

**Comment by billimek** [comment]
This is great news, thank you!
