### ISSUE TITLE
Submit to the official helm charts repo

### ISSUE THREAD

**Issue by billimek** [munnerz/kube-plex#38]
I found [this old issue](https://github.com/helm/charts/issues/3289) but it looks like nothing ever happened with this.

Is there interest in revisiting the inclusion of this plex chart to the [official helm charts repo](https://github.com/helm/charts)?

**Comment by mcronce** [comment]
This would be cool to see.  It looks like only a couple minor changes were needed.  @munnerz I would make a PR to this repo with those changes if it means they'd be submitted to helm/charts - I don't want to take the credit for your work just because I changed a couple lines in a YAML file ;)

**Comment by billimek** [comment]
With the new [helm hub](https://hub.helm.sh/), adding this chart could be a lot easier, it's basically outlined in [this document](https://github.com/helm/hub/blob/master/Repositories.md)

**Comment by billimek** [comment]
The `helm/charts` repo is [being deprecated](https://github.com/helm/charts#deprecation-timeline), so helm hub is the path forward.

@munnerz, I have a solid github actions implementation that will lint and test charts (via KIND) for all pull requests and then automatically publish charts as a repo release.

I'm going to submit a PR to implement the github actions in this in repo, but to fully implement it will require you (or someone else with admin access to this repo) to finalize the implementation.  Specifically, github pages will need to be enabled (ideally using the default `gh-pages` branch), and a github personal access token or equivalent will need to be added as a github actions secret in the repo configuration.

Any issues with this approach?

**Comment by munnerz** [comment]
Sounds good to me 😄 although I'm not too sure what we're best to name the
repo namespace... If we name it 'munnerz' then I'll need to consider how
I'll ever release my own other charts in future given it'll be tied to this
repo 😬

**Comment by billimek** [comment]
I think `munnerz` is fine!  For example, I have a [collection of charts in helm hub](https://hub.helm.sh/charts/billimek) as `billimek` repo, for lack of a better name.  There are similar-personal-named 'repos' in the list there as well.
