### ISSUE TITLE
unknown flag: --name

### ISSUE THREAD

**Issue by rafabiela** [munnerz/kube-plex#71]
Hello everyone
would it be a different way to install?
thanks

helm install ./charts/kube-plex --name plex \                                                                                                         
    --namespace plex \
    --set claimToken=XXX \                       
    --set persistence.data.claimName=existing-pms-data-pvc \
    --set ingress.enabled=true        

Error: unknown flag: --name

**Comment by Kab1r** [comment]
```
helm install plex ./charts/kube-plex \
--namespace plex
--set claimToken=XXX \
--set persistence.data.claimName=existing-pms-data-pvc
--set ingress.enabled=true
```

**Comment by Kab1r** [comment]
Pull Req #72 Fixes this
