### ISSUE TITLE
cert-manager and SSL for reverse proxy, insecure connections

### ISSUE THREAD

**Issue by onedr0p** [munnerz/kube-plex#81]
Edge case here. I have this plex chart up and behind nginx-ingress. However my connections are Insecure when streaming, even though SSL is enabled and working for the Plex Web UI from my `https://plex.mydomain.com` domain.

Does anyone have this working? My guess is I need to add the pfx file to my Plex server settings but I don't know how to obtain this from `cert-manager` (or better yet automated creating a pfx file). Since @munnerz is a maintainer of both these projects maybe he can chime in with some knowledge.

Thanks!

**Comment by runecalico** [comment]
it looks like cert-manager has quite a few requests for this:
https://github.com/jetstack/cert-manager/issues/586
https://github.com/jetstack/cert-manager/issues/2702

and the latest version of cert-manager looks to have some kind of experimental support for generating some  alternative formats
https://cert-manager.io/docs/release-notes/release-notes-0.14/#experimental-bundle-format-support-jks-and-pkcs-12

**Comment by onedr0p** [comment]
Project appears dead, closing.
