### ISSUE TITLE
Kube-plex no longer installing

### ISSUE THREAD

**Issue by kjellmoens** [munnerz/kube-plex#95]
Hi,

I have some scripts to install kube-plex but since the last pull from your repo, the kube-plex does not install anymore. It just goes directly to the web page without giving you the options to setup a server.

Can you please help ?

Thx

**Comment by onedr0p** [comment]
From the amount of reports I think we can gather kube-plex is broken. We're out of luck until a maintainer steps in or @munnerz comes back. Use the flag `--set kubePlex.enabled=false` until it's fixed

**Comment by kjellmoens** [comment]
Well this one is a false alarm. It wasy that did not realize that one of my
pvc was retaining its information.

**Comment by simplyzee** [comment]
Thanks for letting us know it was a false alarm.
Please see reference in regards to transcoder pods - I will close this issue.

https://github.com/munnerz/kube-plex/issues/94#issuecomment-613993411
